scoreboard objectives remove u-shovel
scoreboard objectives remove zu-wshovel
scoreboard objectives remove zu-sshovel
scoreboard objectives remove zu-ishovel
scoreboard objectives remove zu-gshovel
scoreboard objectives remove zu-dshovel
scoreboard objectives remove zu-nshovel
scoreboard objectives remove u-pickaxe
scoreboard objectives remove zu-wpickaxe
scoreboard objectives remove zu-spickaxe
scoreboard objectives remove zu-ipickaxe
scoreboard objectives remove zu-gpickaxe
scoreboard objectives remove zu-dpickaxe
scoreboard objectives remove zu-npickaxe
scoreboard objectives remove u-axe
scoreboard objectives remove zu-waxe
scoreboard objectives remove zu-saxe
scoreboard objectives remove zu-iaxe
scoreboard objectives remove zu-gaxe
scoreboard objectives remove zu-daxe
scoreboard objectives remove zu-naxe
scoreboard objectives remove u-hoe
scoreboard objectives remove zu-whoe
scoreboard objectives remove zu-shoe
scoreboard objectives remove zu-ihoe
scoreboard objectives remove zu-ghoe
scoreboard objectives remove zu-dhoe
scoreboard objectives remove zu-nhoe
scoreboard objectives remove u-sword
scoreboard objectives remove zu-wsword
scoreboard objectives remove zu-ssword
scoreboard objectives remove zu-isword
scoreboard objectives remove zu-gsword
scoreboard objectives remove zu-dsword
scoreboard objectives remove zu-nsword
